### ISSUE TITLE
Filter for Categories

### ISSUE THREAD

**Issue by NordicTux** [jobisoft/CategoryManager#2]
Hello everyone,
it would be nice if there were the posibility to filter incoming mails by categories. Right now I can only filter by "adress is in my adressbook" but not by "adress is in category". I haven't yet found something like elsewhere so I opened this issue here.
Rainer

**Comment by jobisoft** [comment]
I will have a look. That does sound useful.

**Comment by jobisoft** [comment]
I did look into that and it turns out I cannot implement that without changing the source of thunderbird itself. I could add the option to the filter edit dialog, but I cannot change thunderbird to actually do the filtering. 

However there is a way to get this done manually: Use one of the header-modify AddOns and place a custom header into all emails containing the categories the sender is part of. Than use the header filter option of thunderbird. 

From my understanding this cannot be automated on incomming emails, since there is no way to alter incomming emails (headers) automatically and before the thunderbird filter is run. But maybe I am wrong. 

For now, I will not work on this, but I will stay open for pull request.
